const express = require('express')
const routes = express.Router()
const connection = require('./database')
const UsuarioController = require('./controllers/UsuarioController')
const ProdutoController = require('./controllers/ProdutoController')
const PedidoController = require('./controllers/PedidoController')
const ItemController = require('./controllers/ItemController')
const SessionController = require('./controllers/SessionController')

routes.get('/',(request, response)=>{
    response.status(200).send('Seja bem-vindo ao Web Service Fina Massa Homologação')
})
//routes.get('/usuario', UsuarioController.read)
routes.post('/usuario/auth', UsuarioController.auth)
//routes.post('/usuario', UsuarioController.insert)
//routes.put('/usuario/:id/update', UsuarioController.update)
//routes.delete('/usuario/:id', UsuarioController.delete)
routes.get('/produto', ProdutoController.read)
routes.get('/produto/:id', ProdutoController.readByPK)
routes.get('/produto/nome/:nome', ProdutoController.readByName)
routes.get('/produto/ativo/:situacao', ProdutoController.readAtivos)
routes.post('/produto', ProdutoController.insert)
routes.put('/produto/:id/update', ProdutoController.update)
routes.delete('/produto/:id', ProdutoController.delete)
routes.get('/pedido', PedidoController.read)
routes.get('/pedido/:id', PedidoController.readByPk)
routes.get('/pedido/data/:data_ini/:data_fim', PedidoController.readByDate)
routes.post('/pedido', PedidoController.insert)
routes.put('/pedido/:id/update', PedidoController.update)
routes.put('/pedido/:id/registrar', PedidoController.registrarPedido)
routes.put('/pedido/:id/receber', PedidoController.receberPedido)
routes.put('/pedido/:id/reabrir', PedidoController.reabrir)
routes.delete('/pedido/:id', PedidoController.delete)
routes.get('/pedido/:id/itemall', ItemController.read)
routes.get('/pedido/:id/item', ItemController.readByPedido)
routes.post('/pedido/:id/item', ItemController.insert)
routes.put('/pedido/:id/item', ItemController.update)
routes.delete('/item/:id/', ItemController.delete)
routes.get('/session', SessionController.read)
routes.put('/session/:situacao', SessionController.update)
routes.post('/session/:situacao', SessionController.insert)
routes.delete('/session', SessionController.destroy)



module.exports = routes;