const express = require('express')
const routes = express.Router()
const connection = require('./database')
const UsuarioController = require('./controllers/UsuarioController')
const ProdutoController = require('./controllers/ProdutoController')
const PedidoController = require('./controllers/PedidoController')
const ItemController = require('./controllers/ItemController')


routes.get('/usuario', UsuarioController.read)
routes.post('/usuario', UsuarioController.insert)
routes.put('/usuario/:id/update', UsuarioController.update)
routes.delete('/usuario/:id', UsuarioController.delete)
routes.get('/produto', ProdutoController.read)
routes.post('/produto', ProdutoController.insert)
routes.put('/produto/:id/update', ProdutoController.update)
routes.delete('/produto/:id', ProdutoController.delete)
routes.get('/pedido', PedidoController.read)
routes.get('/pedido/:data', PedidoController.readByDate)
routes.post('/pedido', PedidoController.insert)
routes.put('/pedido/:id/update', PedidoController.update)
routes.delete('/pedido/:id', PedidoController.delete)
routes.get('/pedido/:id/itemall', ItemController.read)
routes.get('/pedido/:id/item', ItemController.readByPedido)
routes.post('/pedido/:id/item', ItemController.insert)
routes.put('/pedido/:id/item', ItemController.update)
routes.delete('/item/:id/', ItemController.delete)


module.exports = routes;