const express = require('express')
const routes = express.Router()
const connection = require('./database')
const UsuarioController = require('./controllers/UsuarioController')
const ProdutoController = require('./controllers/ProdutoController')
const PedidoController = require('./controllers/PedidoController')
const ItemController = require('./controllers/ItemController')
const SessionController = require('./controllers/SessionController')

routes.get('/',(request, response)=>{
    response.status(200).send('Seja bem-vindo ao Web Service Fina Massa Homologação')
})
//routes.get('/usuario', UsuarioController.read)
routes.post('/:key/usuario/auth', UsuarioController.auth)
//routes.post('/usuario', UsuarioController.insert)
//routes.put('/usuario/:id/update', UsuarioController.update)
//routes.delete('/usuario/:id', UsuarioController.delete)
// ZmluYW1hc3Nh
routes.get('/:key/produto', ProdutoController.read)
routes.get('/:key/produto/:id', ProdutoController.readByPK)
routes.get('/:key/produto/nome/:nome', ProdutoController.readByName)
routes.get('/:key/produto/ativo/:situacao', ProdutoController.readAtivos)
routes.post('/:key/produto', ProdutoController.insert)
routes.put('/:key/produto/:id/update', ProdutoController.update)
routes.delete('/:key/produto/:id', ProdutoController.delete)
routes.get('/:key/pedido', PedidoController.read)
routes.get('/:key/pedido/:id', PedidoController.readByPk)
routes.get('/:key/pedido/data/:data_ini/:data_fim', PedidoController.readByDate)
routes.post('/:key/pedido', PedidoController.insert)
routes.put('/:key/pedido/:id/update', PedidoController.update)
routes.put('/:key/pedido/:id/registrar', PedidoController.registrarPedido)
routes.put('/:key/pedido/:id/receber', PedidoController.receberPedido)
routes.put('/:key/pedido/:id/reabrir', PedidoController.reabrir)
routes.delete('/:key/pedido/:id', PedidoController.delete)
routes.get('/:key/pedido/:id/itemall', ItemController.read)
routes.get('/:key/pedido/:id/item', ItemController.readByPedido)
routes.post('/:key/pedido/:id/item', ItemController.insert)
routes.put('/:key/pedido/:id/item', ItemController.update)
routes.delete('/:key/item/:id/', ItemController.delete)
routes.get('/:key/session', SessionController.read)
routes.put('/:key/session/:situacao', SessionController.update)
routes.post('/:key/session/:situacao', SessionController.insert)
routes.delete('/:key/session', SessionController.destroy)



module.exports = routes;